publishdir="docs"
baseURL = 'https://ivkin.dev'
languageCode = 'en-us'
theme='anatole'
author="Alexander Ivkin"

[params]
title='Alexander Ivkin'
author="Alexander Ivkin"
profilePicture = "images/ava-london-face.jpg"
description="software developer and entrepreneur"
displayMode = "dark"
pygmentsCodeFences = true
pygmentsUseClasses = true
mainSections = ["posts"]

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/evekeen"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/evekeen"

