publishdir="docs"
baseURL = 'https://ivkin.dev'
languageCode = 'en-us'
theme='anatole'
author="Alexander Ivkin"
disqusShortname="https-ivkin-dev"
gtagId= "G-MYZ5L5XZR9"

[params]
title='Alexander Ivkin'
author="Alexander Ivkin"
profilePicture = "images/ava-pro-300.jpg"
description="indie hacker"
pygmentsCodeFences = true
pygmentsUseClasses = true
mainSections = ["post"]
gtagId= "G-MYZ5L5XZR9"
readMore = true
images = ["images/ava-london-face-small.jpg"]
subscribeUrl = "https://tinyletter.com/ivkin"
subscribeText = "Subscribe"
subscribeTextPost = "Subscribe to this blog"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/alexivkin"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/evekeen"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/evekeen"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[social]
twitter = "alexivkin"
