publishdir="docs"
baseURL = 'https://ivkin.dev'
languageCode = 'en-us'
theme='anatole'
author="Alexander Ivkin"
disqusShortname="https-ivkin-dev"
gtagId= "G-MYZ5L5XZR9"

[params]
title='Alexander Ivkin'
author="Alexander Ivkin"
profilePicture = "images/ava-london-face.jpg"
description="software developer and entrepreneur"
pygmentsCodeFences = true
pygmentsUseClasses = true
mainSections = ["post"]
gtagId= "G-MYZ5L5XZR9"
readMore = true

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/alexivkin"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/evekeen"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/evekeen"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
